// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1zlZpTPPMjhpsVofDcH913mALIUHfF8',
    appId: '1:515488947038:web:507ea575ff7e8dc43b8dcf',
    messagingSenderId: '515488947038',
    projectId: 'mindhealth-e99c8',
    authDomain: 'mindhealth-e99c8.firebaseapp.com',
    storageBucket: 'mindhealth-e99c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDty8MqFo8xIpQmmVbYJfIwY2wAkM7Fixo',
    appId: '1:515488947038:android:8cba602ecd45aef23b8dcf',
    messagingSenderId: '515488947038',
    projectId: 'mindhealth-e99c8',
    storageBucket: 'mindhealth-e99c8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1zlZpTPPMjhpsVofDcH913mALIUHfF8',
    appId: '1:515488947038:web:7815bd38009306e03b8dcf',
    messagingSenderId: '515488947038',
    projectId: 'mindhealth-e99c8',
    authDomain: 'mindhealth-e99c8.firebaseapp.com',
    storageBucket: 'mindhealth-e99c8.appspot.com',
  );
}
